# Generated by Django 3.2.10 on 2021-12-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211228_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='lender',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='lender',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
