# Generated by Django 3.2.10 on 2021-12-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_lender_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lender',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
