# Generated by Django 3.2.10 on 2021-12-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
