# Generated by Django 3.0.6 on 2020-06-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=2000)),
                ('course_code', models.CharField(max_length=4)),
                ('hall', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=20)),
                ('invigilators', models.CharField(max_length=2000)),
            ],
        ),
    ]
