# Generated by Django 3.0.6 on 2020-06-24 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20200624_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='department',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
